@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

SmartNus *-right-> "1" UniqueQuestionList
SmartNus *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueQuestionList
UniqueTagList -[hidden]down- UniqueQuestionList

UniqueTagList *-right-> "*" Tag
UniqueQuestionList -right-> Question

Question -up-> "*" Tag

Question *--> Name
Question *--> Importance
@enduml
