@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlySmartNus <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class SmartNus
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniqueQuestionList
Class NoteList

Class Question
Class Note

Class TagStatistic
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

SmartNus .up.|> ReadOnlySmartNus

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlySmartNus
ModelManager -left-> "1" SmartNus
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

SmartNus *--> "1" UniqueQuestionList
SmartNus *--> "1" NoteList
UniqueQuestionList --> "~* all" Question
NoteList --> "~* all" Note

ModelManager -->"~* filtered" Question
ModelManager -->"~* filtered" TagStatistic
ModelManager -->"~* filtered" Note
@enduml
