@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand
Class ABCCommand

package "Parser classes"{
Interface Parser <<Interface>>
Interface QuizParser <<Interface>>
Class SmartNusParser
Class QuizInputParser
Class XYZCommandParser
Class ABCCommandParser
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> SmartNusParser
HiddenOutside ..> QuizInputParser

SmartNusParser .down.> XYZCommandParser: creates >
QuizInputParser .down.> ABCCommandParser: creates >

XYZCommand -up-|> Command
ABCCommand -up-|> Command
XYZCommandParser ..> XYZCommand : creates >
ABCCommandParser ..> ABCCommand : creates >
QuizInputParser ..> Command : returns >
SmartNusParser ..> Command : returns >
ABCCommandParser .up.|> QuizParser
XYZCommandParser .up.|> Parser
QuizInputParser -right[hidden]- Parser
SmartNusParser -right[hidden]- QuizInputParser
@enduml
