@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SmartNusParser" as SmartNusParser LOGIC_COLOR
participant ":QuizCommandParser" as QuizCommandParser LOGIC_COLOR
participant "d:QuizCommand" as QuizCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("quiz lim/5")
activate LogicManager

LogicManager -> SmartNusParser : parseCommand("quiz lim/5")
activate SmartNusParser

create QuizCommandParser
SmartNusParser -> QuizCommandParser
activate QuizCommandParser

QuizCommandParser --> SmartNusParser
deactivate QuizCommandParser

SmartNusParser -> QuizCommandParser : parse("lim/5")
activate QuizCommandParser

create QuizCommand
QuizCommandParser -> QuizCommand
activate QuizCommand

QuizCommand --> QuizCommandParser : d
deactivate QuizCommand

QuizCommandParser --> SmartNusParser : d
deactivate QuizCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
QuizCommandParser -[hidden]-> SmartNusParser
destroy QuizCommandParser

SmartNusParser --> LogicManager : d
deactivate SmartNusParser

LogicManager -> QuizCommand : execute()
activate QuizCommand

QuizCommand -> Model : updateFilteredQuizQuestionList()
activate Model

Model --> QuizCommand
deactivate Model

create CommandResult
QuizCommand -> CommandResult
activate CommandResult

CommandResult --> QuizCommand
deactivate CommandResult

QuizCommand --> LogicManager : result
deactivate QuizCommand

[<--LogicManager
deactivate LogicManager
@enduml
