@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "SmartNus Storage" #F4F6F6{
Interface SmartNusStorage <<Interface>>
Class JsonSmartNusStorage
Class JsonSerializableSmartNus
Class JsonAdaptedNote
Class JsonAdaptedQuestion
Class JsonAdaptedTag
Class JsonAdaptedChoice
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" SmartNusStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> SmartNusStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonSmartNusStorage .up.|> SmartNusStorage
JsonSmartNusStorage ..> JsonSerializableSmartNus
JsonSerializableSmartNus --> "*" JsonAdaptedQuestion
JsonSerializableSmartNus --> "*" JsonAdaptedNote
JsonAdaptedQuestion --> "*" JsonAdaptedTag
JsonAdaptedQuestion --> "1..*" JsonAdaptedChoice

@enduml
