@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "note note/David is my friend"

package States <<rectangle>> {
    class State1 as "__sn0:SmartNus__"
    class State2 as "__sn1:SmartNus__"
    class State3 as "__sn2:SmartNus__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State3
@end
