@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SmartNusParser" as SmartNusParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant VersionedSmartNus as VersionedSmartNus MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> SmartNusParser : parseCommand(undo)
activate SmartNusParser

create UndoCommand
SmartNusParser -> UndoCommand
activate UndoCommand

UndoCommand --> SmartNusParser
deactivate UndoCommand

SmartNusParser --> LogicManager : u
deactivate SmartNusParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoSmartNus()
activate Model

Model -> VersionedSmartNus : undo()
activate VersionedSmartNus

VersionedSmartNus -> VersionedSmartNus :resetData(ReadOnlySmartNus)
VersionedSmartNus --> Model :
deactivate VersionedSmartNus

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
